. "${BASH_SOURCE%/*}"/devkitppc.sh

export PORTLIBS_PREFIX=${PORTLIBS_ROOT}/gamecube
export PORTLIBS_PPC=${PORTLIBS_ROOT}/ppc
export PORTLIBS_CUBE=${PORTLIBS_PREFIX}

export CPPFLAGS="-D__GAMECUBE__ -I${PORTLIBS_CUBE}/include -I${PORTLIBS_PPC}/include"
export LDFLAGS="-L${PORTLIBS_CUBE}/lib -L${PORTLIBS_PPC}/lib"

export PATH=${PORTLIBS_CUBE}/bin:${PORTLIBS_PPC}/bin:$PATH
